# arquivo responsavel pelo controle de autenticação dos usuarios no servidor Postgresql


#----------METODOS DE AUTENTICAÇÃO-------
TRUST
#CONEXAO SEM REQUISITO DE SENHA
REJECT
#REJEITAR CONEXOES
MD5
#CRIPTOGRAFIA MD5
PASSWORD
SEHA SEM CRIPTOGRAFIA
GSS
#GENERIC SECURITY SERVICE APPLICATION PROGAM INTERFACE
SSPI 
#SECURITY SUPPORT PRIVIDERINTERFACE - SOMENTE PARA WINDOWS
KRB5 
#KERBERUS 5
IDENT
#UTILIZA O USUARIO DO SISTEMA OPERACIONAL DO CLIENTE VIA IDENT SERVER
PEER
#UTILIZA O USUARIO DO S.O. DO CLIENTE
LDAP
#IDAP SERVER
RADIUS 
#RADIUS SERVER
CERT
#AUTENTICAÇÃO VIA CERTIFICADO SSL DO CLIENTE
PAM
#PUGGLABLE AUTHENTICATION MODULES - O USUARIOPRECISA ESTÁ NO BANCO DE DADOS
