# LISTEN_ADDRESSES
#ENDEREÇO TCP/IP DAS INTERFACES QUE O SERVIDOR POSTEGREVAI EXECUTAR / LIBERAR DE ACESSO!

#PORT 
# A PORTA TCP QUE O SERVIDOR POSTGRE VAI OUVIR.POR PADRAO 5432

#MAX_CONNECTION
NUMERO MAXIMO DE CONEXOES SIMULTANEAS QUE O SERVIDOR VAI PERMITIR 

#SUPERUSER_RESERVED_CONNECTIONS
# CONEXÕES DE SUPER USUARIO (SLOTS) RESERVADOS A SUPER USUARIO!

#AUTHENTICATION_TIMEOUT
# O TEMPO MAXIMO EMSEGUNDOS PARA SE CONSSEGUIR UMA CONEXÃO!

# PASSWORD_ENCRYPTATION
# ALGORITIMO DE ENCIPTOGRAFIA DAS SENHAS DOS NOVOS USUARIOS CRIADOS NO BANCO DE DADOS!

# SSL
# HABILITA CONEXÃO COM CRIPTOGRAFIAPOR SSL (SE O BD FOI COMPILADO COM SUPORTE SSL)

#SHARED_BUFFERS
#TAMANHO DA MEMORIA COMPARTILHADA DO SERVIDOR POSTGRESSQL PARA CACHE/BUFFER DE TABELAS INDICES DE DEMAIS RELAÇÕES!

#WORK_MEM
# TAMANHO DA MEMORIA PARA OPERAÇÕES DE AGRUPAMENTOE ORDENAÇÕES(ORDEN BY, DISTINCT, MERGE JOYNS)

#MAINTENANCE_WORK_MEM
# TAMANHO DA MEMORIA PARA OPERAÇÕES COMO VACUUM, INDEX, ALTER TABLE

#
